name = "exampleproj"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Main"]
testDriver = "ExampleprojTest"


[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"


[[lean_lib]]
name = "ExampleprojTest"

[[lean_lib]]
name = "Exampleproj"

[[lean_exe]]
name = "Main"